import { useMemo } from 'react'
import { MechanicalPanel } from '../../mechanical/MechanicalPanel'
import { TechnicalLabel } from '../../typography/TechnicalLabel'
import { SystemIndicator } from '../../telemetry/SystemIndicator'
import { useRepresentation } from '../../../app/providers/RepresentationProvider'
import type { EngineeringSystem } from '../../../data/home'
import { EngineeringSystemSelector } from './EngineeringSystemSelector'
import { ThermodynamicsInstrument } from './ThermodynamicsInstrument'
import { FluidMechanicsInstrument } from './FluidMechanicsInstrument'
import { EngineeringFlowDiagram } from './EngineeringFlowDiagram'
import { ManufacturingInstrument } from './ManufacturingInstrument'
import { RoboticsInstrument } from './RoboticsInstrument'
import './engineeringLab.css'
export function EngineeringLab({systems,selectedSystem,onSelectSystem}:{systems:EngineeringSystem[];selectedSystem:string;onSelectSystem:(id:string)=>void}){const {isBlueprint}=useRepresentation();const selected=useMemo(()=>systems.find(s=>s.id===selectedSystem)||systems[0],[systems,selectedSystem]);const thermo=selected.id==='thermodynamics';const fluid=selected.id==='fluid';const manufacturing=selected.id==='manufacturing';const robotics=selected.id==='robotics';return <div className={`engineering-lab ${isBlueprint?'is-blueprint':'is-reality'}`}><div className="engineering-lab__topline"><TechnicalLabel prefix="LAB">ENGINEERING SYSTEMS</TechnicalLabel><span className="technical-small">REPRESENTATION / {isBlueprint?'BLUEPRINT':'REALITY'}</span></div><div className="engineering-lab__layout"><EngineeringSystemSelector systems={systems} selectedSystem={selected.id} onSelectSystem={onSelectSystem}/><div className="engineering-lab__instrument">{thermo?<ThermodynamicsInstrument/>:fluid?<FluidMechanicsInstrument/>:manufacturing?<ManufacturingInstrument/>:robotics?<RoboticsInstrument/>:<MechanicalPanel variant="highlighted" className="engineering-lab__preview"><div className="engineering-lab__preview-head"><TechnicalLabel prefix="SYSTEM">AVAILABLE</TechnicalLabel><SystemIndicator state="idle" label="PREVIEW"/></div><span className="technical-small">SYSTEM / {selected.id.toUpperCase()}</span><h3>{selected.title}</h3><p className="body-small">{selected.description}</p><div className="engineering-lab__preview-metric"><span className="technical-small">CURRENT DOMAIN</span><strong>{selected.metric}</strong></div><p className="technical-small">INTERACTIVE MODULE / NEXT SYSTEM</p></MechanicalPanel>}</div></div>{thermo&&<EngineeringFlowDiagram active/>}</div>}
