import { useEffect,useRef,useState } from 'react'
import { CursorTarget } from '../../interaction/CursorTarget'
import { TechnicalLabel } from '../../typography/TechnicalLabel'
import { useReducedMotion } from '../../../hooks/useReducedMotion'
import { useRepresentation } from '../../../app/providers/RepresentationProvider'
import { clampHeat,calculateThermodynamics } from './thermodynamics'
import { ThermodynamicsReadout } from './ThermodynamicsReadout'
const COUNT=54
export function ThermodynamicsInstrument(){const [heat,setHeat]=useState(35);const [visible,setVisible]=useState(false);const ref=useRef<HTMLDivElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const reduced=useReducedMotion();const {isBlueprint}=useRepresentation();const model=calculateThermodynamics(heat)
useEffect(()=>{const n=ref.current;if(!n)return;const o=new IntersectionObserver(([e])=>setVisible(e.isIntersecting),{rootMargin:'160px 0px',threshold:.01});o.observe(n);return()=>o.disconnect()},[])
useEffect(()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const ps=Array.from({length:COUNT},(_,i)=>({x:.24+(i*.071)% .52,y:.22+(i*.137)%.48,vx:((i%5)-2)*.0009,vy:(((i*3)%7)-3)*.0008,p:i*.91}));let raf=0,last=performance.now();const draw=(now:number)=>{const dt=Math.min(32,now-last);last=now;drawScene(ctx,c,ps,heat,isBlueprint,now,reduced?0:dt);if(visible&&!reduced)raf=requestAnimationFrame(draw)};const resize=()=>{const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);drawScene(ctx,c,ps,heat,isBlueprint,performance.now(),0)};resize();if(visible&&!reduced)raf=requestAnimationFrame(draw);window.addEventListener('resize',resize);return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize)}},[visible,reduced,heat,isBlueprint])
const adjust=(d:number)=>setHeat(v=>clampHeat(v+d));return <div ref={ref} className={`thermo-instrument ${isBlueprint?'is-blueprint':'is-reality'}`}><div className="thermo-instrument__visual"><canvas ref={canvasRef} aria-hidden="true"/><div className="thermo-instrument__labels" aria-hidden="true"><span>HEAT / INPUT</span><span>STATE / {model.state}</span><span>PISTON AXIS</span><span>ENERGY → WORK</span></div><div className="thermo-instrument__chamber" aria-hidden="true"><div className="thermo-instrument__piston" style={{transform:`translateY(${model.pistonPosition*.34}%)`}}/><div className="thermo-instrument__rod" style={{height:`${18+model.pistonPosition*.2}%`}}/><div className="thermo-instrument__heat-source" style={{opacity:.2+heat/150}}/></div></div><div className="thermo-instrument__controls"><div className="thermo-control"><div className="thermo-control__head"><TechnicalLabel prefix="ADJUST">HEAT INPUT</TechnicalLabel><output htmlFor="heat-input">{heat} %</output></div><div className="thermo-control__rail"><CursorTarget label="HEAT" intent="view"><button type="button" onClick={()=>adjust(-5)} aria-label="Decrease heat input by 5 percent">−</button></CursorTarget><input id="heat-input" type="range" min="0" max="100" step="1" value={heat} onChange={e=>setHeat(Number(e.target.value))} aria-label="Heat input, 0 to 100 percent"/><CursorTarget label="HEAT" intent="view"><button type="button" onClick={()=>adjust(5)} aria-label="Increase heat input by 5 percent">+</button></CursorTarget></div><div className="thermo-control__scale technical-small"><span>0 / IDLE</span><span>50 / ACTIVE</span><span>100 / HIGH</span></div></div><ThermodynamicsReadout model={model}/></div></div>}
function drawScene(ctx:CanvasRenderingContext2D,c:HTMLCanvasElement,ps:{x:number;y:number;vx:number;vy:number;p:number}[],heat:number,blueprint:boolean,now:number,dt:number){const w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);const line=blueprint?'rgba(130,169,199,.72)':'rgba(201,208,211,.5)';ctx.strokeStyle=line;ctx.lineWidth=1;const x=w*.2,y=h*.17,cw=w*.6,ch=h*.6;ctx.strokeRect(x,y,cw,ch);ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(w*.5,y-25);ctx.lineTo(w*.5,y+ch+25);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle=blueprint?'rgba(130,169,199,.34)':'rgba(216,164,95,.5)';ctx.beginPath();ctx.moveTo(w*.34,h*.86);ctx.lineTo(w*.66,h*.86);ctx.stroke();const count=w<520?28:COUNT;const speed=.35+heat/100*1.8;for(let i=0;i<count;i++){const p=ps[i];if(dt){p.x+=(p.vx*speed+Math.sin(now*.002+p.p)*.0018*speed)*dt;p.y+=(p.vy*speed+Math.cos(now*.0017+p.p)*.0015*speed)*dt;if(p.x<.23||p.x>.77)p.vx*=-1;if(p.y<.22||p.y>.72)p.vy*=-1;p.x=Math.max(.23,Math.min(.77,p.x));p.y=Math.max(.22,Math.min(.72,p.y))}ctx.fillStyle=blueprint?'rgba(169,196,216,.82)':`rgba(237,241,242,${.24+heat/180})`;ctx.beginPath();ctx.arc(w*p.x,h*p.y,1.3+speed*.8,0,Math.PI*2);ctx.fill()}ctx.strokeStyle=blueprint?`rgba(130,169,199,${.2+heat/180})`:`rgba(216,164,95,${.16+heat/130})`;ctx.beginPath();ctx.moveTo(w*.5,h*.87);ctx.lineTo(w*.5,h*.75);ctx.stroke()}
